# Generated by Django 5.2.5 on 2025-09-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_weight', models.FloatField(default=0)),
                ('sludge_weight', models.FloatField(default=0)),
                ('sl_rcy_expense', models.FloatField(default=0)),
                ('dust_weight', models.FloatField(default=0)),
                ('dus_rcy_expense', models.FloatField(default=0)),
                ('sl_buyer', models.CharField(max_length=100, null=0)),
                ('dus_buyer', models.CharField(max_length=100, null=0)),
                ('sl_profit', models.FloatField(default=0)),
                ('dus_profit', models.FloatField(default=0)),
                ('rcy_team', models.CharField(max_length=100, null=0)),
            ],
        ),
    ]
