# Generated by Django 5.2.5 on 2025-09-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_records',
            name='Waste_BD',
            field=models.DateField(null=True),
        ),
    ]
