# Generated by Django 5.2.5 on 2025-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_waste_records_waste_bd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste_records',
            old_name='dus_buyer',
            new_name='Dus_buyer',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='dus_profit',
            new_name='Dus_profit',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='dus_rcy_expense',
            new_name='Dus_rcy_expense',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='dust_weight',
            new_name='Dust_weight',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='rcy_team',
            new_name='Rcy_team',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='sl_buyer',
            new_name='Sl_buyer',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='sl_profit',
            new_name='Sl_profit',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='sl_rcy_expense',
            new_name='Sl_rcy_expense',
        ),
        migrations.RenameField(
            model_name='waste_records',
            old_name='sludge_weight',
            new_name='Sludge_weight',
        ),
        migrations.AddField(
            model_name='waste_records',
            name='Dus_rcyp_ED',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='waste_records',
            name='Sl_rcyp_ED',
            field=models.DateField(null=True),
        ),
    ]
