# Generated by Django 5.2.5 on 2025-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_dus_buyer_waste_records_dus_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste1_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Waste_BD', models.DateField(null=True)),
                ('Total_weight', models.FloatField(default=0)),
                ('Sludge_weight', models.FloatField(default=0)),
                ('Sl_rcy_expense', models.FloatField(default=0)),
                ('Sl_rcyp_ED', models.DateField(null=True)),
                ('Dust_weight', models.FloatField(default=0)),
                ('Dus_rcy_expense', models.FloatField(default=0)),
                ('Dus_rcyp_ED', models.DateField(null=True)),
                ('Sl_buyer', models.CharField(max_length=100, null=0)),
                ('Dus_buyer', models.CharField(max_length=100, null=0)),
                ('Sl_profit', models.FloatField(default=0)),
                ('Dus_profit', models.FloatField(default=0)),
                ('Rcy_team', models.CharField(max_length=100, null=0)),
            ],
        ),
    ]
