# Generated by Django 5.2.5 on 2025-09-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_waste10_records_waste11_records_waste12_records_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waste10_records',
        ),
        migrations.DeleteModel(
            name='Waste11_records',
        ),
        migrations.DeleteModel(
            name='Waste12_records',
        ),
        migrations.DeleteModel(
            name='Waste13_records',
        ),
        migrations.DeleteModel(
            name='Waste14_records',
        ),
        migrations.DeleteModel(
            name='Waste15_records',
        ),
        migrations.DeleteModel(
            name='Waste16_records',
        ),
        migrations.DeleteModel(
            name='Waste17_records',
        ),
        migrations.DeleteModel(
            name='Waste1_records',
        ),
        migrations.DeleteModel(
            name='Waste2_records',
        ),
        migrations.DeleteModel(
            name='Waste3_records',
        ),
        migrations.DeleteModel(
            name='Waste4_records',
        ),
        migrations.DeleteModel(
            name='Waste5_records',
        ),
        migrations.DeleteModel(
            name='Waste6_records',
        ),
        migrations.DeleteModel(
            name='Waste7_records',
        ),
        migrations.DeleteModel(
            name='Waste8_records',
        ),
        migrations.DeleteModel(
            name='Waste9_records',
        ),
    ]
