# Generated by Django 5.2.5 on 2025-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_waste10_records_delete_waste11_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste_records',
            name='Dus_buyer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waste_records',
            name='Rcy_team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='waste_records',
            name='Sl_buyer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
