# Generated by Django 5.2.5 on 2025-09-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_waste1_records'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waste1_records',
        ),
    ]
