# Generated by Django 5.2.5 on 2025-09-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_waste1_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waste_records',
            new_name='Steel_records',
        ),
    ]
