# Generated by Django 5.2.5 on 2025-09-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_waste_records_steel_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='steel_records',
            name='Place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
