# Generated by Django 5.2.5 on 2025-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_steel_records_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steel1_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dust_weight', models.FloatField(default=0)),
                ('Dus_rcy_expense', models.FloatField(default=0)),
                ('Dus_rcyp_ED', models.DateField(null=True)),
                ('Sl_buyer', models.CharField(max_length=100, null=True)),
                ('Dus_buyer', models.CharField(max_length=100, null=True)),
                ('Sl_profit', models.FloatField(default=0)),
                ('Dus_profit', models.FloatField(default=0)),
                ('Rcy_team', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
