# Generated by Django 5.2.5 on 2025-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_dus_rcyp_ed_steel10_records_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steel10_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel11_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel12_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel1_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel2_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel3_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel4_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel5_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel6_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel7_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel8_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel9_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='steel_records',
            name='Task',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
