# Generated by Django 5.2.5 on 2025-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_steel10_records_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steel_records',
            name='Task',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
